include(cmake/version_config.cmake)

if(CCACHE_ENABLE)
	find_program(CCACHE_FOUND ccache)
	if(CCACHE_FOUND)
		set_property(GLOBAL PROPERTY RULE_LAUNCH_COMPILE ccache)
		set_property(GLOBAL PROPERTY RULE_LAUNCH_LINK ccache)
	endif(CCACHE_FOUND)
endif()

if (DEBUG_ENABLE)
	message(STATUS "Building in DEBUG mode.")
	add_definitions(-DDEBUG=1)
	set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -O0")
	
else()
	message(STATUS "Building in RELEASE mode.")
	set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -O3")
endif()
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -g")

macro(global_set_flags)
	if (MYC_FOO_SUPPORT)
		add_definitions(-DMYC_FOO_SUPPORT)
	endif()
	if (MYC_BOO_SUPPORT)
		add_definitions(-DMYC_BOO_SUPPORT)
	endif()
endmacro()