option(CCACHE_ENABLE "Enable ccache" ON)
if ("${CMAKE_BUILD_TYPE}" STREQUAL "debug")
	option(DEBUG_ENABLE "Enable debug mode" ON)
endif()
option(MYC_FOO_SUPPORT "Support foo" ON)
option(MYC_BOO_SUPPORT "Support boo" OFF)